apiVersion: v2
name: app
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: backend
    version: 0.1.0
    repository: file://charts/backend
  - name: frontend
    version: 0.1.0
    repository: file://charts/frontend
  - name: mongo
    version: 0.1.0
    repository: file://charts/mongo
  - name: postgres
    version: 0.1.0
    repository: file://charts/postgres