apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres-user: "{{ .Values.secrets.postgresUser }}"
  postgres-password: "{{ .Values.secrets.postgresPassword }}"